name: multimodal-captions
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - torchvision
  - tqdm
  - wandb
  - datasets
  - transformers
  - pytorch
